name: TRMNL Server
version: "0.1.0"
slug: trmnl-server
description: Self-hosted TRMNL display server for e-ink devices
url: https://github.com/jptrsn/home-assistant-add-ons
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
options:
  refresh_interval: 300
schema:
  refresh_interval: int(60,3600)
homeassistant_api: true
hassio_api: true
hassio_role: default
ingress: true
ingress_port: 8080
panel_icon: mdi:monitor-dashboard