name: "USB Multi-Mounter"
slug: "usb_mounter"
version: "0.1.0"
description: "Automatically mounts configured USB drives to persistent mount points."
url: "https://github.com/jptrsn/home-assistant-add-ons/usb-mounter"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "services"
boot: "auto"
init: false
map:
  - media:rw
  - share:rw
options:
  drives: []
schema:
  drives:
    - device: str
      label: str
      mount_point: str
